#train example
srun --mem 1200000 --time 168:00:00 --ntasks 1 --cpus-per-task 7 --partition bse --gres=gpu:tesla-a100:1 python3 ./DivShift/temp_elena_src/supervised_train.py --device 0 --data_dir ./west_coast_dataset --checkpoint_freq 5 --exp_id spatial_split_train_spatial_split_test_Supervised --num_epochs 10 --batch_size 64 --test_batch_size 64 --learning_rate 0.064 --processes 4 --train_type full_finetune --train_split spatial_split --test_split spatial_split --to_classify name

srun --mem 1200000 --time 168:00:00 --ntasks 1 --cpus-per-task 7 --partition bse --gres=gpu:tesla-a100:1 python3 ./DivShift/temp_elena_src/supervised_train.py --device 0 --data_dir ./west_coast_dataset --checkpoint_freq 5 --exp_id inat2021_train_inat2021_test_Supervised --num_epochs 10 --batch_size 64 --test_batch_size 64 --learning_rate 0.064 --processes 4 --train_type full_finetune --train_split inat2021 --test_split inat2021 --to_classify name

srun --mem 1200000 --time 168:00:00 --ntasks 1 --cpus-per-task 7 --partition bse --gres=gpu:tesla-a100:1 python3 ./DivShift/temp_elena_src/supervised_train.py --device 0 --data_dir ./west_coast_dataset --checkpoint_freq 5 --exp_id inat2021mini_train_inat2021mini_test_Supervised --num_epochs 10 --batch_size 64 --test_batch_size 64 --learning_rate 0.064 --processes 4 --train_type full_finetune --train_split inat2021mini --test_split inat2021mini --to_classify name

srun --mem 1200000 --time 168:00:00 --ntasks 1 --cpus-per-task 7 --partition bse --gres=gpu:tesla-a100:1 python3 ./DivShift/temp_elena_src/supervised_train.py --device 0 --data_dir ./west_coast_dataset --checkpoint_freq 5 --exp_id imagenet_train_imagenet_test_Supervised --num_epochs 10 --batch_size 64 --test_batch_size 64 --learning_rate 0.064 --processes 4 --train_type full_finetune --train_split imagenet --test_split imagenet --to_classify name

srun --mem 1200000 --time 168:00:00 --ntasks 1 --cpus-per-task 7 --partition bse --gres=gpu:tesla-a100:1 python3 ./DivShift/temp_elena_src/supervised_train.py --device 0 --data_dir ./west_coast_dataset --checkpoint_freq 5 --exp_id taxonomic_balanced_train_taxonomic_balanced_test_Supervised --num_epochs 10 --batch_size 64 --test_batch_size 64 --learning_rate 0.064 --processes 4 --train_type full_finetune --train_split taxonomic_balanced --test_split taxonomic_balanced --to_classify name

srun --mem 1200000 --time 168:00:00 --ntasks 1 --cpus-per-task 7 --partition bse --gres=gpu:tesla-a100:1 python3 ./DivShift/temp_elena_src/supervised_train.py --device 0 --data_dir ./west_coast_dataset --checkpoint_freq 5 --exp_id taxonomic_unbalanced_train_taxonomic_unbalanced_test_Supervised --num_epochs 10 --batch_size 64 --test_batch_size 64 --learning_rate 0.064 --processes 4 --train_type full_finetune --train_split taxonomic_unbalanced --test_split taxonomic_unbalanced --to_classify name

# test only
srun --mem 120000 --time 168:00:00 --ntasks 1 --cpus-per-task 7 --partition bse --gres=gpu:1 python3 ./DivShift/temp_elena_src/supervised_test_only.py --device 0 --data_dir ./west_coast_dataset --test_batch_size 64 --learning_rate 0.064 --processes 4 --to_classify name --exp_id Quality_train_Casual_test_Supervised --train_split quality_obs --test_split casual_obs --train_saved_weights ./DivShift_supervised_results/Quality_train_Quality_test_Supervised_10epochs_2024-08-09/Quality_train_Quality_test_Supervised_10epochs_2024-08-09_epoch9.pth

srun --mem 120000 --time 168:00:00 --ntasks 1 --cpus-per-task 7 --partition bse --gres=gpu:1 python3 ./DivShift/temp_elena_src/supervised_test_only.py --device 0 --data_dir ./west_coast_dataset --test_batch_size 64 --learning_rate 0.064 --processes 4 --to_classify name --exp_id wilderness_train_modified_test_Supervised --train_split footprint_wilderness --test_split footprint_modified --train_saved_weights ./DivShift_supervised_results/wilderness_train_wilderness_test_Supervised_2024-08-13/wilderness_train_wilderness_test_Supervised_2024-08-13_epoch9.pth

srun --mem 120000 --time 168:00:00 --ntasks 1 --cpus-per-task 7 --partition bse --gres=gpu:1 python3 ./DivShift/temp_elena_src/supervised_test_only.py --device 0 --data_dir ./west_coast_dataset --test_batch_size 64 --learning_rate 0.064 --processes 4 --to_classify name --exp_id not_city_nature_train_city_nature_test_Supervised --train_split not_city_nature --test_split city_nature --train_saved_weights ./DivShift_supervised_results/NotCN_train_NotCN_test_Supervised_10epochs_2024-08-08/NotCN_train_NotCN_test_Supervised_10epochs_2024-08-08_epoch9.pth